modLoader="javafml"
license="LGPLv3"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/AntimatterAPI/issues"

[[mods]]
modId="antimatter"
version="${file.jarVersion}"
displayName="AntimatterAPI"
displayURL="https://github.com/GregTech-Intergalactical/AntimatterAPI"
#logoFile="examplemod.png"
credits="mitchej123, e99999, qubka, Vliro, repolainen, Trinsdar for general implementations/fixes"
authors="Muramasa, Rongmario"
description='''Well-rounded API for Minecraft, primarily made for GregTech.'''
[[dependencies.antimatter]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.antimatter]]
    modId="tesseract"
    mandatory=true
    versionRange="[0.0.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.antimatter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"